### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Eldar2021** [AppITCompany/kurs15#1]
# Kurs 15 Roadmap

## Dart Basics
- [ ] Dart Overview
  - [ ] What is Dart Programming?
  - [ ] Dart Tutorial
  - [ ] About Dart
  - [ ] What is Dart?
  - [ ] Dart in 100 Seconds

- [ ] DartPad
  - [ ] [DartPad](https://dart.dev/tools/dartpad)
  - [ ] DartPad in Tutorials
